GET http://localhost:3000/posts


###


POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "keko",
    "password": "123qweasd"
}


###


GET http://localhost:3000/users